{% set version = "0.1.4" %}
{% set name = "atmosphere-virtual-lab" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stcorp/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 46b266bb27dbf981f36231c15061b93a8e2a720cf82b0030e223f37c0f54fda2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux64]

  host:
    - python >=3.9
    - pip

  run:
    - jupyterlab >=3
    - jupytext
    - python >=3.9
    - requests
    - coda
    - ipyleaflet-gl-vector-layer-plugin
    - ipyleaflet =0.15.0
    - harp
    - panel =0.12.7
    - pyproj
    - vtk >=9.1
    - plotly
    - numpy
    - scipy

test:
  imports:
    - avl

about:
  home: https://github.com/stcorp/atmosphere-virtual-lab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Atmosphere Virtual Lab

extra:
  recipe-maintainers:
    - srepmub
    - svniemeijer
