{% set name = "atmosphere-virtual-lab" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stcorp/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4d7b42dd0bd779256252ab24d75915affc6a21349f29a8769fe61eef2ecfceff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}

  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - beamf
    - cartopy
    - cmap
    - cmcrameri
    - coda
    - doas_cl
    - eofetch
    - fsspec
    - harp
    - importlib_resources
    - ipyleaflet
    - ipyleaflet-gl-vector-layer-plugin >=0.1.6
    - jupyterlab >=3
    - jupytext
    - matplotlib-base
    - numpy
    - panel
    - plotly
    - pyproj
    - python >={{ python_min }}
    - qdoas2harp
    - requests
    - scipy
    - vtk >=9.1
    - xarray
    - zarr

test:
  requires:
    - python {{ python_min }}
  imports:
    - avl

about:
  home: https://github.com/stcorp/atmosphere-virtual-lab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Atmosphere Virtual Lab

extra:
  recipe-maintainers:
    - svniemeijer
