{% set name = "atmosphere-virtual-lab" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stcorp/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 09165fbaf747c642dc36659f014e0266cb7f8e708421341a5a0e8b9218640c0e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux64]

  host:
    - python >=3.7
    - pip

  run:
    - beamf
    - cmcrameri
    - coda
    - harp
    - ipyleaflet
    - ipyleaflet-gl-vector-layer-plugin >=0.1.6
    - jupyterlab >=3
    - jupytext
    - matplotlib-base
    - numpy
    - panel
    - plotly
    - pyproj
    - python >=3.7
    - qdoas
    - qdoas2harp
    - requests
    - scipy
    - vtk >=9.1

test:
  imports:
    - avl

about:
  home: https://github.com/stcorp/atmosphere-virtual-lab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Atmosphere Virtual Lab

extra:
  recipe-maintainers:
    - srepmub
    - svniemeijer
