{% set version = "0.1.8" %}
{% set name = "atmosphere-virtual-lab" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stcorp/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: bcae7f663affcd77faba44309b064864e49ad31a3bee9404a8fcb4865f1b622e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux64]

  host:
    - python >=3.7
    - pip

  run:
    - jupyterlab >=3
    - jupytext
    - python >=3.7
    - requests
    - coda
    - ipyleaflet-gl-vector-layer-plugin
    - ipyleaflet
    - harp
    - panel
    - pyproj
    - vtk >=9.1
    - plotly
    - numpy
    - scipy
    - matplotlib

test:
  imports:
    - avl

about:
  home: https://github.com/stcorp/atmosphere-virtual-lab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Atmosphere Virtual Lab

extra:
  recipe-maintainers:
    - srepmub
    - svniemeijer
